### ISSUE TITLE
OpenMod installer must have another command

### ISSUE THREAD

**Issue by kulkaGM** [openmod/OpenMod.Installer.RocketMod#6]
When we install OpenMod Module with this plugin for RocketMod, it works fine...

But after that, the OpenMod command not working at all 
(Yes it is working for the Installer like when you want uninstall OpenMod with the installer,
but not for the OpenMod Module) because is it reserved from the RocketMod plugin **OpenMod Installer** in RocketMod Commands.config.xml

So the command name for installer should be renamed like to `OpenModModule` (Or to something else)
(After this the installer can install or uninstall OpenMod Module with simple `OpenModModule install/uninstall` and OpenMod Module can finally use the `OpenMod` command alias

**Comment by Trojaner** [comment]
Turned out OpenMod did not load. This issue wont happen if OpenMod loads as OpenMod overrides RocketMod commands
